#################   DATASET CONFIG   ###################


project_name: "mcocr"
data_root: "data/"
train_annotation: "train_line_annotation.txt"
valid_annotation: "test_line_annotation.txt"
data_export: "./data"

print_every: 100
valid_every: 500
iters: 20000
export: "./weights/transformerocr.pth"


#################   TRAINING CONFIG   ###################

gpu_devices: "cuda:0"
model_name: "vgg_transformer"
